/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/new-landscape.glb -T -o src/components-3d/NewLandscape.jsx 
Files: public/models/new-landscape.glb [48.06KB] > C:\Users\tarbl\Documents\Software Dev\!Projects\three.js-personal-website\src\components-3d\new-landscape-transformed.glb [21.52KB] (55%)
*/

import React from 'react'
import { useGLTF, useKTX2 } from '@react-three/drei'

export function NewLandscape(props) {
  const { nodes } = useGLTF('/models/new-landscape-transformed.glb')
  const bakedTexture = useKTX2('/textures/landscape.ktx2')
  bakedTexture.flipY = false

  return (
    <group {...props} dispose={null} scale={100}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Map.geometry}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/new-landscape-transformed.glb')
