/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/train.glb -o src/components-3d/Train.jsx 
*/

import React from 'react'
import { useGLTF, useTexture } from '@react-three/drei'

export function Train(props) {
  const { nodes } = useGLTF('/models/train.glb')
  const bakedTexture = useTexture('/textures/train.jpg')
  bakedTexture.flipY = false

  return (
    <group {...props} dispose={null} scale={100}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.train.geometry}
        position={[-2.65, 0.206, 1.494]}
        rotation={[1.603, 0.001, 1.589]}
        scale={0.285}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/train.glb')
